name: Deploy to Neocities

on:
  push:
    branches:
      - main # Trigger this action only with commits on the 'main' branch.


concurrency: # Prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Neocities # You can customize this if you want
        uses: bcomnes/deploy-to-neocities@master # Ensure this action is compatible with Node20
        with:

          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true # true: delete Neocities files that don't exist in the repo. false: ignore these files
          dist_dir: public # The folder in which the site is located